name: main

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: devops_toolkit:latest 
          outputs: type=docker,dest=/tmp/devops_toolkit.tar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker_image 
          path: /tmp/devops_toolkit.tar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3 
        with:
          name: devops_toolkit
          path: /tmp
      - name: Load Image
        run: docker load --input /tmp/devops_toolkit.tar
      - name: Docker Logon
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - name: Tag image
        run: docker tag devops_toolkit weslleystein/devops_toolkit
      - name: Image Push
        run: docker push weslleystein/devops_toolkit
